### ISSUE TITLE
Spaltenüberschriften der Tabellen für Überblick (Journal) und Produkte passt nicht

### ISSUE THREAD

**Issue by dabo5** [anti43/openyabs#14]
Hi,
hab ein Problem mit den Spaltenüberschriften im Journal. Auf deutsch passt es hier nicht:
![detusch](https://cloud.githubusercontent.com/assets/7451448/2843734/a1f37364-d082-11e3-8003-6955fcf5084b.JPG)
hier das englische original:
![engl](https://cloud.githubusercontent.com/assets/7451448/2843736/a21c4bb8-d082-11e3-80d8-044553d124ba.JPG)

Hab das Gefühl, das es nicht nur an einer fehlerhaften Sprachdatei liegt.

Bei der Produkliste werden überhaupt keine Überschriften angezeigt:
![deutsch_prod](https://cloud.githubusercontent.com/assets/7451448/2843735/a215afb0-d082-11e3-97e4-09c3e0f349c9.JPG)

Gruß

**Comment by anti43** [comment]
Bitte in der aktuellen Version noch einmal testen, danke!

**Comment by anti43** [comment]
.. oder Issue schliessen
