### ISSUE TITLE
DB Upgrade problem

### ISSUE THREAD

**Issue by christau** [anti43/openyabs#17]
I recently updated to the newest version and had the problem, that the value field of table ValueProperties was gone.
The [code](https://github.com/anti43/openyabs/blob/1f60f37b49fed73c032394b9932345b89f10168e/src/mpv5/db/common/DatabaseUpdater.java#L344) to upgrade the DB reads

```
UPDATES_MYSQL.put(1.1842, new String[]{
"ALTER TABLE valueproperties DROP COLUMN value",
"ALTER TABLE valueproperties ADD COLUMN value LONGBLOB DEFAULT NULL"
});
```

i simply replaced it with

```
UPDATES_MYSQL.put(1.1842, new String[]{
            "alter table `valueproperties` modify column `value` longblob null AFTER `objectids`",
        });
```

and it also worked without dropping that field.
It's not really an issue, but it lets you lose some data on upgrade.
Thanks anyway for the code!

**Comment by anti43** [comment]
will this work when there is data in the column already?
