### ISSUE TITLE
Yabs akzeptiert keine Templates

### ISSUE THREAD

**Issue by VirToReal** [anti43/openyabs#18]
Soll z.B eine Rechnung über LibreOffice in ein PDF Umgewandelt werden mithilfe des definierten Templates, friert das Fenster von Yabs ein, und im Terminal wird folgendes ausgegeben:

Done with local settings file: /home/hardy/.yabs/settings0.yabs
Registering class mpv5.ui.frames.MPView
ITEMS [1]
ITEMS [1]
CONTACTS [6]
{bankaccount=, bankcountry=, bankcurrency=, bankid=, bankname=, city=Test, cname=Test, cnumber=000001, company=, country=Deutschland, dateadded=2015-02-01, deliveryaddress=000001, department=, fax=, fullname=Test Test, gender=Herr, group=All Groups, intaddedby=1, intro=Sehr geehrter, invoiceaddress=000001, iscompany=false, iscustomer=true, isenabled=true, ismale=true, ismanufacturer=false, issupplier=false, mailaddress=, mainphone=, mobilephone=, notes=, prename=Test, street=Erlenstraße 11, taxnumber=, title=, website=, workphone=, zip=92712}
CONTACTS [6]
ADDRESSES [16]
ADDRESSES [16]
ADDRESSES [16]
ADDRESSES [16]
Feb 01, 2015 2:42:37 PM ag.ion.bion.officelayer.internal.application.connection.LocalOfficeConnection openConnection
INFORMATION: Opening local OpenOffice.org connection.
CE> Warning: -nologo is deprecated.  Use --nologo instead.
CE> Warning: -nodefault is deprecated.  Use --nodefault instead.
CE> Warning: -norestore is deprecated.  Use --norestore instead.
CE> Warning: -nolockcheck is deprecated.  Use --nolockcheck instead.
CE> Warning: -accept=socket,host=localhost,port=8100;urp; is deprecated.  Use --accept=socket,host=localhost,port=8100;urp; instead.
select count(ids) from groups
select count(ids) from groups

dabei wird die letzte Zeile im langen Intervallen wiederholt. Ich hab es auch mit älteren Versionen von LibreOffice/OpenOffice probiert, jedoch ohne erfolg. Was kann man dagegen tun?

**Comment by anti43** [comment]
Hallo,

das liegt an OpenOffice, wir erarbeiten gerade eine Lösung ohne Libre/Openoffice. die Versionen verhalten sich einfach zu unterschiedlich :/

**Comment by HardRainbow** [comment]
Oh das etwas dran gemacht wird hört sich ja wunderbar an :+1:

**Comment by johanneshk** [comment]
Stehe gerade (scheinbar) vor demselben Problem: Gibt es etwas neues? Gibt es Libre Office Versionen die sicher gehen sollten?

**Comment by anti43** [comment]
nein, wir arbeiten an einer version komplett ohne office.

**Comment by digger-bw** [comment]
Die aktuelle Version unterstützt die Office unabhängige Version. Bitte testet das mal bei euch. 
Dazu bitte unter Werkzeuge -> externe Programme die Optionen "Kein Open Office verwenden" und "es wird ein eigener odt/PDF Generator benutzt" aktivieren alle anderen Checkboxen dort deaktivieren.

**Comment by digger-bw** [comment]
Ergänzung: Das kann beim erstenmal seeeeeeehr lange dauern da die systemeigenen Schriftarten gecached werden ...

**Comment by ecxod** [comment]
[CUZA-20160004.pdf](https://github.com/anti43/openyabs/files/573987/CUZA-20160004.pdf)
So ich hab das mal gemacht, ich habe "Kein Open Office verwenden" und "es wird ein eigener odt/PDF Generator benutzt" angekreuzt jetzt sieht eine Rechnung so aus (siehe Anlage)
[CUZA-20160004.pdf](https://github.com/anti43/openyabs/files/573988/CUZA-20160004.pdf)

**Comment by digger-bw** [comment]
Sieht nach einem Font-Problem aus ... kann ich von dir mal die selbe Datei als ODT-Export haben ?

**Comment by ecxod** [comment]
aber sicher :)

**Comment by digger-bw** [comment]
Oder musterdaten einmal als PDF und einmal als odt ... dann kann ich die als testcase an den PDF-converter hängen ...

**Comment by magischeweide** [comment]
Hi, I don't fix it to get fields filled for a reminder .odt file created with libreOffice. The table gets some characters I don't know. Creating an Invoice works fine.
[zahlung.pdf](https://github.com/anti43/openyabs/files/4627578/zahlung.pdf)
