### ISSUE TITLE
VORSCHLAG: Vorlagen aus der Datenbank.

### ISSUE THREAD

**Issue by ecxod** [anti43/openyabs#21]
@anti43 Ich nutze das Yabs im lokalen Netzwerk. Es wäre super wenn die Vorlagen in der Datenbank gespeichert wären. Also laden aus einer lokalen *odt ( ooffice oder Libreoffice zum erstellen der Vorlage ist OK ) , aber nach dem ersten "laden" sollte die Vorlage aus der Datenbank kommen.
Es wäre schön wenn jemand der sich mit Vorlagen auskennt einige professionelle Vorlagen bastelt und hochladet.

**Comment by anti43** [comment]
Hi, ist das denn nicht so ?

**Comment by digger-bw** [comment]
... Ich denke schon aber es gibt eine Option die lokale Dateien auf Änderungen überwachen und die dB aktualisieren soll ...

**Comment by ecxod** [comment]
so kann man keine flüssige Diskussion führen wenn einer am 9.August eine Frage stellt und am 5 November eine Gegenfrage bekommt.
BTW, der Login muss endlich verändert werden so dass er Login-Daten speichern kann.
Es ist ein Krampf jedes mal User und Password einzugeben. Ein Login Manager wäre angebracht, wie zB bei FileZilla.
Werkzeuge >> Einstellungen >> Vorlagen Manager
rechts unten:
Vorlagen überwachen und ggf aktualisieren
Pfad zur Datei. [......]
Die Vorlage liegt auf meinem Rechner. Ich konnte von einem anderen Rechner im Netzwerk nicht auf diese Vorlage zugreifen. Die Vorlage sollte aus einem Bolb aus der Datenbank kommen.

**Comment by digger-bw** [comment]
die u.g. Funktion bezieht sich auf die Änderungen einer DB-gespeicherten Vorlage aus dem Filesystem heraus. Die Vorlage zum Druck (oder Export) sollte aus der DB kommen …

bei mir sind lokal gar keine Dateien mehr vorhanden…. Wie lautet denn die Fehlermeldung?

**Comment by ecxod** [comment]
OK, ich habe es irgendwie verstanden, jetzt werde ich mal Yabs in einer neuen VM installieren. Ich werde das reproduzieren, und dann melde ich mich.

**Comment by digger-bw** [comment]
Ich antworte jetzt mal direkt aus git da irgendwie bei mir nur die ersten 2 Zeilen per Mail angekommen sind ...

Nicht ganz ...: es muss einmal ein Template importiert und den jeweiligen Benutzern zugewiesen werden (also jeweils für Rechnung, Angebot etc) fertig ...
Danach KANN die lokale Änderung der lokalen Datei die hochgeladen wurde überwacht werden (von Yabs automatisch) und Änderungen werden wieder in die DB geschrieben. 

ich lese aus der letzten Antwort das es mehrere Benutzer von Yabs gibt. Die Templates müssen JEDEM Benutzer der es benutzen soll zugewiesen werden ...

**Comment by anti43** [comment]
Die Vorlagen (Templates) werden aktuell in der Datenbank gespeichert, sie müssen nur dem User zugewiesen werden.
