### ISSUE TITLE
Yabs simply don't start.

### ISSUE THREAD

**Issue by ecxod** [anti43/openyabs#22]
Sometimes Yabs simply don't start.
How can I untherstand why it does not want to start?

(zu deutsch: Yabs bricht ab und zu beim Start Sang und Klanglos ab.
Wie kann ich herausfinden was ihm nicht gefallen hat?)

**Comment by anti43** [comment]
yabs im terminal starten:  java -jar yabs.jar -debug -consolelog

**Comment by ecxod** [comment]
C:\Users\Christian\Yabs-1.2.6-beta1-package> java -jar yabs.jar -debug -consolelog
An error has occurred while processing the shared archive file.
Unable to unmap shared space.
Error occurred during initialization of VM
Unable to use shared archive.

**Comment by anti43** [comment]
sorry, den fehler hab ich  noch nie gesehen
