### ISSUE TITLE
Yabs auf high-DPI display

### ISSUE THREAD

**Issue by pbek** [anti43/openyabs#24]
Vielen Dank für diese tolle Software!

Weiß jemand eine Möglichkeit Yabs auf einem high-DPI display unter Linux auszuführen ohne dass die Anwendung winzig klein angezeigt wird (wird an Java liegen)?

**Comment by anti43** [comment]
keine Ahnung :)

http://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display

Am 22. Februar 2017 um 09:26 schrieb Patrizio Bekerle <
notifications@github.com>:

**Comment by pbek** [comment]
`-Dsun.java2d.dpiaware=false` hat leider nicht geholfen... :)

**Comment by anti43** [comment]
Ghet das:

Find java.exe you installed.
Right click -> Properties
Go to Compatibility tab
Check Override high DPI scaling behavior.
Choose System for Scaling performed by:

**Comment by anti43** [comment]
Fixed with java10 support in release 1.3.x
