### ISSUE TITLE
yabs starts - with a blank window

### ISSUE THREAD

**Issue by thw-mate** [anti43/openyabs#25]
Hi,
I tried to install the package - on Linux Mint - yabs starts - but only with an empty window. Is there a way to solve that issue?

regards thw

**Comment by digger-bw** [comment]
Hi,

I don't know this behavior but maybe some Parameter in the environment are bad for yabs.

Please start yabs with enabled conselelog-option. Maybe there are some background informations mentioned in the log.

Kind regards jan

**Comment by thw-mate** [comment]
Hi,
sry - noobalart ;) tried to figure out what to type, to do that.... but got no clue
regards thw

**Comment by thw-mate** [comment]
is the issue still open?

**Comment by thw-mate** [comment]
Hi, 
sry, I do not know much about Linux - still searching for neccessary commands :)

**Comment by digger-bw** [comment]
Hi,

Ok … please start yabs with the command line java -jar yabs.jar -debug -consolelog 

regards Jan

**Comment by digger-bw** [comment]
you closed the issue  today ... i'll reopen it

**Comment by thw-mate** [comment]
ty :)

popup-error:
"Missing needed lib(s)! Exiting Program!
went on with installation
same popup-error again
second one with
"Table/view ’PRODUCTODERSUBITEMS’ does not exist"

but now everything seems to work fine :)
thx ;)

**Comment by digger-bw** [comment]
Ok ... assuming that this is a new installation with derby... please try the libs out of this package 
http://de.gofile.me/2bNeg/sharing/4sEQlIPWd?tunnel=/tunnel/
(Just copy the files from / to the lib- folder)

For the error 'productordersubitems': 
Which version of yabs you're using ?

**Comment by thw-mate** [comment]
Hi,
a) yes, it's a new installation
b) yes, with derby
c) version: 1.2.7.1

...
I copied the files to the /yabs/libs folder (yabs is on my "schreibtisch") - same error "Productodersubitems"

**Comment by anti43** [comment]
fixed in latest release
